# Generated by Django 5.0.2 on 2024-03-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='sab')),
                ('discription', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=30)),
                ('movie_runtime', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
